<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>TimerMod</AssemblyName>
    <Product>Mod that has timer in it</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TimerMod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="lib\*.dll" Private="False" />
  </ItemGroup>
</Project>
